[package]

name = "rback"
version = "0.0.2"
authors = ["davidb"]

[lib]
name = "rback"

[dependencies]
libc = "0.2"
toml = "0.1.26"
error-type = "0.1.2"
rustc-serialize = "0.3.16"
# log = "0.1"

# [dependencies.sudo]
# path = "src/sudo"

[[bin]]
name = "rback"
test = false
doc = false
